name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - pip=20.3.3
  - scikit-learn=0.24.1
  - numpy=1.23.4
  - protobuf=3.20.*
  - pip:
      - wandb==0.10.21